name: crcmanip

on: [push, pull_request]

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pre-commit pytest
        python -m pip install -e .
    - name: Check formatting
      run: |
        pre-commit run -a
    - name: Run tests
      run: |
        pytest
